version: '3.8'
services:
    frontend:
        container_name: container-production
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5173:5173'
        volumes:
            - './:/app'
            - /app/node_modules
